services:
  db:
    image: postgres:17.6
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      TZ: Asia/Kolkata

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
    ports:
      - "5432:5432"

  web:
    build: ./web
    container_name: flask_web
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
      FACE_SERVICE_URL: http://face_service:8000
      TZ: Asia/Kolkata
    volumes:
      - ./web:/app
    restart: always

  face_service:
    build: ./face_service
    container_name: face_service
    environment:
      WEB_SERVICE_URL: http://web:5000
      TZ: Asia/Kolkata
    volumes:
      - ./face_service:/app
    ports:
      - "8000:8000"

volumes:
  db_data:
